apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless 
  labels:
    app: postgres
spec:
  clusterIP: None #As mentioned in problem statement, it is a headless service
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
