apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-data-internal #A subpath is provided as there were conflicts with redeployment and data overwrites
        envFrom:
        - secretRef:
            name: postgres-credentials
        - configMapRef:
            name: postgres-config
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
