apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api  
  minReplicas: 3  
  maxReplicas: 6 
  targetCPUUtilizationPercentage: 50 #Threshold is lowered to 50% in HPA for demonstration purpose
