apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
data:
  POSTGRES_USER: cG9zdGdyZXM= #Base64 encoded values
  POSTGRES_PASSWORD: cG9zdGdyZXM= #Base64 encoded values
type: kubernetes.io/opaque
