apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80 #Host port is changed for ease of use
    
    targetPort: 8080
  type: LoadBalancer #API is exposed using load balancer